### ISSUE TITLE
DSA module

### ISSUE THREAD

**Issue by yan-ctrl** [whwu95/DSANet#1]
Hello, I didn't see that the DSA module is used in the I3D network. Am I wrong

**Comment by whwu95** [comment]
Thank you for your interest in our project. Regarding the model architecture, we used I3D, which stands for a 3x1x1 + 1x3x3 spatiotemporal convolution structure. You can find the specific backbone code for the recognizer [here](https://github.com/whwu95/DSANet/blob/main/codes/models/recognizers/recognizer3d.py).

Let me know if you have any further questions or if there's anything else I can help with.

**Comment by yan-ctrl** [comment]
OK, thank you. I see it. So your data processing is: b, u, c, t, h, w, is u the number of video clips? T is the number of frames input per clip? Am I right?

**Comment by whwu95** [comment]
> OK, thank you. I see it. So your data processing is: b, u, c, t, h, w, is u the number of video clips? T is the number of frames input per clip? Am I right?

Just to clarify, U refers to the number of clips in our model.

**Comment by yan-ctrl** [comment]
Ok, thank you for your patience
